### ISSUE TITLE
cannot find the dataset "VTKG-I","VTKG-C"

### ISSUE THREAD

**Issue by Lllllivia** [bdi-lab/VISTA#1]
cannot find the dataset "VTKG-I","VTKG-C",
without the dataset, i cannot run the bash command
could you please tell me whether the dataset  is available?
thx a lot

**Comment by jaejunlee714** [comment]
Hi, thanks for your interest in our work.

As you can find in the readme of our repository, you can download our dataset in the following link.
https://drive.google.com/file/d/1u4QthmEboMzRarF_HLYfLDOLcOZeH8Gp/view?usp=drive_link

Thank you.
